name: Run Benchmark
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - develop

jobs:
  build:
    name: "Bazel Build and Benchmark"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up Python 3.9 # Install Python 3.9 for the environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Download Benchmark Script
        run: |
          wget https://elasticbeanstalk-us-east-1-734046833946.s3.amazonaws.com/gha_add_rows_ti.py
          chmod +x gha_add_rows_ti.py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib gspread

      - name: Save Current Time to File
        run: |
          echo "$(date +"%Y-%m-%d %H:%M:%S")" > time_record.txt
          echo "Timestamp saved to time_record.txt"

      - name: Bazel Build
        run: bazel build //...

      - name: Run Bazel Tests
        run: bazel test //...

      - name: Upload Benchmark Duration
        run: python gha_add_rows_ti.py
        env:
          BASE64_GCP_KEY: ${{ secrets.BASE64_GCP_KEY }}
          WORKSHEET_INDEX: ${{ secrets.WORKSHEET_INDEX }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
