name: Benchmark
on:
  pull_request: {}
  workflow_dispatch: {}
  
permissions:
  contents: read
  id-token: write

jobs:
  build-with-ut:
    name: Build with UT
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 
      - name: Test UTs
        continue-on-error: true
        run: |
          mvn clean install -DskipITs -Dmaven.test.failure.ignore=true -DfailIfNoTests=false
